### ISSUE TITLE
Any way to set a device (FanLinc, LEDBulb,...) to linking mode via insteon-terminal?, 

### ISSUE THREAD

**Issue by jtmoderate876** [pfrommerd/insteon-terminal#9]

**Comment by berndpfrommer** [comment]
I just pushed a change that will allow you to instantiate a device of type FanLinc. It has a enterLinkingMode() command implemented. Nothing tested as I do not have a device like that.
So in your init.py you would have two lines like this:

from fanlinc import *
kp         = FanLinc("kp", "30.0d.9f")

and then you try this from the command line:

>>> kp.enterLinkingMode()
sent msg: OUT:Cmd:0x62|toAddress:30.0D.9F|messageFlags:0x0F=DIRECT:3:3|command1:0x09|command2:0x01|
linking mode got msg: IN:Cmd:0x50|fromAddress:30.0D.9F|toAddress:23.9B.65|messageFlags:0xAB=NACK_OF_DIRECT:3:2|command1:0x09|command2:0xFD|

Since I don't have the fanlinc, I used the keypadlinc instead. That command is supposed to work for both the fanlinc and the keypadlinc. Looks like it doesn't work for the keypadlinc, since it  responds with "NACK" (that means "NOPE" in Insteon world). There is a good chance it won't work for the fanlinc either. But it's supposed to!

The other question: why do you want to do that? You can directly link the devices with insteon terminal.

**Comment by jtmoderate876** [comment]
Thanks Berndt.
I was trying to Linc several devices tu a new plm USB modem and wanted to avoid climbing ladders.

Can new devices be linked (put in linking mode) using insteon terminal without the push button dance? How please?

**Comment by berndpfrommer** [comment]
If you have two PLM modems (or a hub + modem), you can link a new modem to a device, using the old modem. This is done with the "addResponder()" and "addController()" methods. But if you are starting from scratch you will have to press the buttons, at least for most devices I tried. I think this is for security reasons.

**Comment by jtmoderate876** [comment]
That is great to know.
I can use terminal with my existing, already linked hub2014 to set devices as responders to the new PLM.

I could have avoided the ladders and ceiling fans/lights disassembly yesterday.

I didn't think of that, thanks.

Sincerely, Jeff Tapia
